name: Update gist with WakaTime stats
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manually run'
        required: true
        default: 'warning'
      tags:
        description: 'Manually run waka box'  
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 2f848d6edb1e841a1c4c61f48881f3f8
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
